[book]
title = "Sepia Documentation"
description = "File-system-based serialization library for Crystal"
authors = ["Roberto Alsina"]
language = "en"
multilingual = false
src = "book"

[build]
build-dir = "docs/book"

[output.html]
git-repository-url = "https://github.com/ralsina/sepia"
edit-url-template = "https://github.com/ralsina/sepia/edit/main/{path}"

[output.html.search]
enable = true
limit-results = 30

[output.html.fold]
enable = false

